name: 'setup-uv'
description: 'Installs uv and synchronizes the project dependencies.'

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        version: "0.11"
        enable-cache: true
        cache-dependency-glob: |
          ./pyproject.toml
          ./uv.lock

    - name: Install all Python dependencies into a virtual environment
      shell: bash
      run: uv sync --locked
